"""Add username column to users table

Revision ID: 4c6cd68282a5
Revises: d4761e5a8c6a
Create Date: 2024-02-06 14:38:07.292309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c6cd68282a5'
down_revision: Union[str, None] = 'd4761e5a8c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
